apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

images:
  - name: ghcr.io/robbertvdzon/software-factory-backend
    newName: localhost/software-factory-backend
    newTag: main
  - name: ghcr.io/robbertvdzon/software-factory-frontend
    newName: localhost/software-factory-frontend
    newTag: main

patches:
  - target:
      kind: Deployment
      name: software-factory-backend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
      name: software-factory-frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
