apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

images:
  - name: ghcr.io/robbertvdzon/softwarefactory-dashboard-backend
    newName: localhost/softwarefactory-dashboard-backend
    newTag: main
  - name: ghcr.io/robbertvdzon/softwarefactory-dashboard-frontend
    newName: localhost/softwarefactory-dashboard-frontend
    newTag: main

patches:
  - target:
      kind: Deployment
      name: softwarefactory-dashboard-backend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
      name: softwarefactory-dashboard-frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
