apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: software-factory

resources:
- sealed-secret.yaml
- database.yaml
- attachments-pvc.yaml
- software-factory-backend-deployment.yaml
- software-factory-backend-service.yaml
- software-factory-frontend-deployment.yaml
- software-factory-frontend-service.yaml
- software-factory-route.yaml

images:
- name: ghcr.io/robbertvdzon/software-factory-backend
  newName: ghcr.io/robbertvdzon/software-factory-backend
  newTag: sha-56bed73
- name: ghcr.io/robbertvdzon/software-factory-frontend
  newName: ghcr.io/robbertvdzon/software-factory-frontend
  newTag: sha-ffaf623
