apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: softwarefactory-dashboard
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/robbertvdzon/software-factory.git
    targetRevision: master
    path: deploy/base
  destination:
    server: https://kubernetes.default.svc
    namespace: software-factory
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
